name: ggmolvis-docs
channels:

  - conda-forge

dependencies:
    # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
  - jupyter_contrib_nbextensions
  - nbsphinx
  - pandoc
    # Pip-only installs
  #- pip:
